# Generated by Django 4.2 on 2023-04-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_desciption_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='featured_image',
            new_name='item_image',
        ),
    ]
